openapi: 3.0.3
info:
  title: SmartSeller API - Admin Drop Point Claim Management
  description: |
    Admin drop point claim management endpoints for warranty claim processing.
    These endpoints are used by drop point admins to manage warranty claims assigned to their drop points.
  version: 1.0.0

servers:
  - url: https://api.smartseller.com/v1
    description: Production server
  - url: https://staging-api.smartseller.com/v1
    description: Staging server
  - url: http://localhost:8090/v1
    description: Development server

security:
  - BearerAuth: []

paths:
  /api/v1/admin/drop-points/claims:
    get:
      tags:
        - Admin Drop Points
      summary: List assigned claims
      description: |
        Retrieve all warranty claims assigned to the drop point admin.
        Shows claims from all drop points assigned to the admin.
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, validated, rejected, replaced, completed]
          description: Filter by claim status
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
          description: Items per page
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [created_at, updated_at, claim_date, status]
            default: created_at
          description: Sort field
        - name: sort_direction
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort direction
      responses:
        '200':
          description: Claims retrieved successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: './warranty-schemas.yaml#/components/schemas/WarrantyClaim'
                      pagination:
                        $ref: './common.yaml#/components/schemas/PaginationInfo'
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'
        '500':
          $ref: './common.yaml#/components/responses/InternalServerError'

  /api/v1/admin/drop-points/claims/{id}:
    get:
      tags:
        - Admin Drop Points
      summary: Get claim details
      description: Retrieve detailed information about a specific warranty claim.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Claim ID
      responses:
        '200':
          description: Claim details retrieved
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        $ref: './warranty-schemas.yaml#/components/schemas/WarrantyClaim'
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'
        '404':
          $ref: './common.yaml#/components/responses/NotFound'

  /api/v1/admin/drop-points/claims/{id}/validate:
    post:
      tags:
        - Admin Drop Points
      summary: Validate warranty claim
      description: |
        Validate a warranty claim and approve it for processing.
        This transitions the claim from 'pending' to 'validated' status.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Claim ID
        - name: validation
          in: body
          required: true
          schema:
            type: object
            required:
              - validation_notes
            properties:
              validation_notes:
                type: string
                maxLength: 1000
                description: Notes about the validation decision
                example: "Screen damage verified, customer documentation complete"
              replacement_cost:
                type: number
                format: decimal
                description: Estimated replacement cost
                example: 150.00
              requires_replacement:
                type: boolean
                description: Whether this claim requires product replacement
                example: true
      responses:
        '200':
          description: Claim validated successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          claim:
                            $ref: './warranty-schemas.yaml#/components/schemas/WarrantyClaim'
        '400':
          $ref: './common.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'
        '404':
          $ref: './common.yaml#/components/responses/NotFound'

  /api/v1/admin/drop-points/claims/{id}/reject:
    post:
      tags:
        - Admin Drop Points
      summary: Reject warranty claim
      description: |
        Reject a warranty claim with a specified reason.
        This transitions the claim to 'rejected' status.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Claim ID
        - name: rejection
          in: body
          required: true
          schema:
            type: object
            required:
              - rejection_reason
            properties:
              rejection_reason:
                type: string
                maxLength: 1000
                description: Reason for rejecting the claim
                example: "Warranty period expired on 2023-11-20"
              admin_notes:
                type: string
                maxLength: 1000
                description: Additional notes for the customer
                example: "Customer informed about expired warranty. Offered paid repair options."
      responses:
        '200':
          description: Claim rejected successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          claim:
                            $ref: './warranty-schemas.yaml#/components/schemas/WarrantyClaim'
        '400':
          $ref: './common.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'
        '404':
          $ref: './common.yaml#/components/responses/NotFound'

  /api/v1/admin/drop-points/claims/{id}/generate-replacement:
    post:
      tags:
        - Admin Drop Points
      summary: Generate replacement barcode
      description: |
        Generate a new replacement barcode for a validated claim.
        Supports both warranty carry-over and reset options.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Claim ID
        - name: replacement
          in: body
          required: true
          schema:
            type: object
            properties:
              warranty_action:
                type: string
                enum: [carry_over, reset]
                default: carry_over
                description: Warranty action for replacement
                example: carry_over
              warranty_extension_months:
                type: integer
                minimum: 0
                maximum: 12
                description: Additional warranty months (only for carry_over)
                example: 1
              notes:
                type: string
                maxLength: 500
                description: Notes about the replacement
                example: "Customer provided positive feedback, adding 1 month as goodwill"
      responses:
        '201':
          description: Replacement barcode generated
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        $ref: './warranty-schemas.yaml#/components/schemas/WarrantyBarcode'
        '400':
          $ref: './common.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'
        '404':
          $ref: './common.yaml#/components/responses/NotFound'
        '422':
          description: Cannot generate replacement for this claim
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/ErrorResponse'

  /api/v1/admin/drop-points/claims/{id}/execute-replacement:
    post:
      tags:
        - Admin Drop Points
      summary: Execute barcode replacement
      description: |
        Execute the actual replacement by assigning the new barcode.
        This completes the claim and marks it as 'replaced'.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Claim ID
        - name: execution
          in: body
          required: true
          schema:
            type: object
            required:
              - replacement_barcode_id
            properties:
              replacement_barcode_id:
                type: string
                format: uuid
                description: ID of the replacement barcode to assign
              replacement_notes:
                type: string
                maxLength: 1000
                description: Notes about the replacement process
                example: "Original screen replaced with OEM part. Functionality tested and verified."
              resolution_type:
                type: string
                enum: [replace, repair]
                default: replace
                description: Type of resolution
      responses:
        '200':
          description: Replacement executed successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          claim:
                            $ref: './warranty-schemas.yaml#/components/schemas/WarrantyClaim'
                          replacement_record:
                            type: object
                            properties:
                              old_barcode:
                                type: string
                                example: "REX25ABCDEF123456"
                              new_barcode:
                                type: string
                                example: "REX25XYZ789012345"
                              replacement_date:
                                type: string
                                format: date-time
        '400':
          $ref: './common.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'
        '404':
          $ref: './common.yaml#/components/responses/NotFound'

  /api/v1/admin/drop-points/profile:
    get:
      tags:
        - Admin Drop Points
      summary: Get drop point admin profile
      description: |
        Retrieve profile information for the drop point admin,
        including assigned drop points and statistics.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          admin:
                            type: object
                            properties:
                              id:
                                type: string
                                format: uuid
                              name:
                                type: string
                              email:
                                type: string
                          drop_points:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: string
                                  format: uuid
                                name:
                                  type: string
                                code:
                                  type: string
                                address:
                                  type: string
                                is_primary:
                                  type: boolean
                          statistics:
                            type: object
                            properties:
                              total_claims:
                                type: integer
                              pending_claims:
                                type: integer
                              validated_claims:
                                type: integer
                              replaced_claims:
                                type: integer
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './common.yaml#/components/responses/Forbidden'

  /api/v1/admin/drop-points/barcodes/{id}/replacements:
    get:
      tags:
        - Admin Drop Points
      summary: Get barcode replacement history
      description: |
        Retrieve the complete replacement history for a warranty barcode.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Barcode ID
      responses:
        '200':
          description: Replacement history retrieved
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './common.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          barcode:
                            $ref: './warranty-schemas.yaml#/components/schemas/WarrantyBarcode'
                          replacements:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: string
                                  format: uuid
                                old_barcode_number:
                                  type: string
                                new_barcode_number:
                                  type: string
                                replacement_date:
                                  type: string
                                  format: date-time
                                warranty_action:
                                  type: string
                                claim_id:
                                  type: string
                                  format: uuid
        '401':
          $ref: './common.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './common.yaml#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token required for authentication.
        Token must have 'is_admin' flag set to true.
        Drop point admins must have appropriate permissions assigned.