openapi: 3.0.3
info:
  title: SmartSeller Admin Customer API
  description: |
    Admin API for customer management including loyalty information.
    This API provides endpoints for administrators to view and manage customers.
  version: 1.0.0
  contact:
    name: SmartSeller Team
    email: support@smartseller.com

servers:
  - url: http://localhost:8090/api/v1
    description: Development server
  - url: https://api.smartseller.com/api/v1
    description: Production server

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Loyalty Account Information
    LoyaltyAccountInfo:
      type: object
      description: Loyalty account information for a customer
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the loyalty account
          example: "550e8400-e29b-41d4-a716-446655440001"
        current_balance:
          type: integer
          description: Current available points balance
          example: 10000
        pending_points:
          type: integer
          description: Points that are pending confirmation
          example: 0
        available_balance:
          type: integer
          description: Points available for redemption (current_balance - pending_points)
          example: 10000
        total_points_earned:
          type: integer
          description: Total lifetime points earned
          example: 15000
        total_points_redeemed:
          type: integer
          description: Total lifetime points redeemed
          example: 5000
        total_points_expired:
          type: integer
          description: Total lifetime points that have expired
          example: 0
        current_tier:
          type: string
          enum: [bronze, silver, gold, platinum]
          description: Current loyalty tier
          example: "silver"
        tier_start_date:
          type: string
          format: date-time
          description: Date when the current tier was achieved
          example: "2024-01-15T10:30:00Z"
        status:
          type: string
          enum: [active, inactive, suspended, frozen]
          description: Loyalty account status
          example: "active"
        lifetime_orders_count:
          type: integer
          description: Total number of orders placed by the customer
          example: 25
        lifetime_spend:
          type: number
          format: float
          description: Total amount spent by the customer
          example: 5000000.00
        referral_count:
          type: integer
          description: Number of successful referrals
          example: 5
        review_count:
          type: integer
          description: Number of product reviews submitted
          example: 3

    # Customer Details Response
    CustomerDetailResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        storefront_id:
          type: string
          format: uuid
          example: "660e8400-e29b-41d4-a716-446655440000"
        email:
          type: string
          format: email
          nullable: true
          example: "customer@example.com"
        phone:
          type: string
          nullable: true
          example: "+62812345678"
        first_name:
          type: string
          nullable: true
          example: "John"
        last_name:
          type: string
          nullable: true
          example: "Doe"
        full_name:
          type: string
          nullable: true
          example: "John Doe"
        date_of_birth:
          type: string
          format: date
          nullable: true
          example: "1990-01-15"
        gender:
          type: string
          enum: [male, female, other, prefer_not_to_say]
          nullable: true
          example: "male"
        email_verified_at:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-15T10:30:00Z"
        phone_verified_at:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-15T10:30:00Z"
        last_login_at:
          type: string
          format: date-time
          nullable: true
          example: "2024-12-01T15:30:00Z"
        status:
          type: string
          enum: [active, inactive, blocked]
          example: "active"
        customer_type:
          type: string
          enum: [regular, vip, wholesale]
          example: "regular"
        tags:
          type: array
          items:
            type: string
          example: ["vip", "repeat_buyer"]
        accepts_marketing:
          type: boolean
          example: true
        total_orders:
          type: integer
          example: 10
        total_spent:
          type: number
          format: float
          example: 2500000.00
        average_order_value:
          type: number
          format: float
          example: 250000.00
        last_order_date:
          type: string
          format: date-time
          nullable: true
          example: "2024-11-15T10:30:00Z"
        notes:
          type: string
          nullable: true
          example: "VIP customer, prefers express shipping"
        created_at:
          type: string
          format: date-time
          example: "2023-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-12-01T15:30:00Z"
        # Loyalty Information
        loyalty_account:
          $ref: '#/components/schemas/LoyaltyAccountInfo'
        has_loyalty_account:
          type: boolean
          description: Whether the customer has a loyalty account
          example: true

    # Error Response
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Operation failed"
        error:
          type: string
          example: "not_found"
        meta:
          type: object
          properties:
            http_status:
              type: integer
              example: 404

    # Success Response Wrapper
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Operation completed successfully"

tags:
  - name: Admin Customers
    description: Admin customer management operations

paths:
  /admin/customers/{id}:
    get:
      tags:
        - Admin Customers
      summary: Get customer details
      description: |
        Retrieve detailed information about a specific customer including their loyalty account information.
        If the customer has a loyalty account, loyalty details will be included in the response.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Customer ID
          example: "550e8400-e29b-41d4-a716-446655440000"
        - name: storefront_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: |
            Storefront ID (optional, defaults to admin's storefront).
            Use this to override the storefront context.
          example: "660e8400-e29b-41d4-a716-446655440000"
        - name: storefront_slug
          in: query
          required: false
          schema:
            type: string
          description: |
            Storefront slug (optional, alternative to storefront_id).
            Use this to override the storefront context.
          example: "rexus"
      responses:
        '200':
          description: Customer details retrieved successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CustomerDetailResponse'
              examples:
                with_loyalty:
                  value:
                    success: true
                    message: "Customer retrieved successfully"
                    data:
                      id: "550e8400-e29b-41d4-a716-446655440000"
                      storefront_id: "660e8400-e29b-41d4-a716-446655440000"
                      email: "customer@example.com"
                      phone: "+62812345678"
                      first_name: "John"
                      last_name: "Doe"
                      full_name: "John Doe"
                      status: "active"
                      customer_type: "regular"
                      tags: ["vip", "repeat_buyer"]
                      accepts_marketing: true
                      total_orders: 10
                      total_spent: 2500000.00
                      average_order_value: 250000.00
                      has_loyalty_account: true
                      loyalty_account:
                        id: "550e8400-e29b-41d4-a716-446655440001"
                        current_balance: 10000
                        pending_points: 0
                        available_balance: 10000
                        total_points_earned: 15000
                        total_points_redeemed: 5000
                        total_points_expired: 0
                        current_tier: "silver"
                        tier_start_date: "2024-01-15T10:30:00Z"
                        status: "active"
                        lifetime_orders_count: 25
                        lifetime_spend: 5000000.00
                        referral_count: 5
                        review_count: 3
                without_loyalty:
                  value:
                    success: true
                    message: "Customer retrieved successfully"
                    data:
                      id: "550e8400-e29b-41d4-a716-446655440000"
                      storefront_id: "660e8400-e29b-41d4-a716-446655440000"
                      email: "newcustomer@example.com"
                      first_name: "Jane"
                      last_name: "Smith"
                      full_name: "Jane Smith"
                      status: "active"
                      customer_type: "regular"
                      total_orders: 0
                      total_spent: 0.00
                      has_loyalty_account: false
                      loyalty_account: null
        '400':
          description: Bad request - invalid customer ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Authorization failed - invalid storefront context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
