openapi: 3.0.3
info:
  title: Admin Shopify Integrations API
  version: 1.0.0
paths:
  /api/v1/admin/storefronts/{id}/integrations/shopify:
    get:
      summary: List Shopify integrations for a storefront
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopifyIntegrationListResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
    put:
      summary: Upsert Shopify integration for a storefront
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopifyIntegrationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopifyIntegrationResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /api/v1/admin/storefronts/{id}/integrations/shopify/{integration_id}:
    delete:
      summary: Delete Shopify integration by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: integration_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
  /api/v1/admin/storefronts/{id}/shopify/sync-products:
    post:
      summary: Trigger Shopify product sync (upsert)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 250
            default: 50
        - in: query
          name: domain
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopifySyncProductsResult'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway
  /api/v1/admin/storefronts/{id}/shopify/sync-orders:
    post:
      summary: Trigger Shopify order sync (upsert)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 250
            default: 50
        - in: query
          name: domain
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShopifySyncOrdersResult'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway
components:
  schemas:
    ShopifyIntegrationRequest:
      type: object
      required: [store_domain, access_token]
      properties:
        store_domain:
          type: string
          example: wisnu-development.myshopify.com
        access_token:
          type: string
          example: shpat_****************
        api_version:
          type: string
          example: 2024-10
        status:
          type: string
          enum: [active, disabled]
        scopes:
          type: array
          items: { type: string }
    ShopifyIntegrationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        storefront_id:
          type: string
          format: uuid
        store_domain:
          type: string
        api_version:
          type: string
        status:
          type: string
        scopes:
          type: array
          items: { type: string }
        has_token:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ShopifyIntegrationListResponse:
      type: object
      properties:
        integrations:
          type: array
          items:
            $ref: '#/components/schemas/ShopifyIntegrationResponse'
    ShopifySyncProductsResult:
      type: object
      properties:
        total_fetched:
          type: integer
        created_count:
          type: integer
        skipped_count:
          type: integer
        failed_count:
          type: integer
    ShopifySyncOrdersResult:
      type: object
      properties:
        total_fetched:
          type: integer
        created_count:
          type: integer
        updated_count:
          type: integer
        skipped_count:
          type: integer
        failed_count:
          type: integer